name: Build and Deploy Sphinx Docs

on:
  push:
    branches:
      - main # Или твоя основная ветка

permissions:
  contents: write # Необходимо для деплоя в gh-pages

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Выбери нужную версию Python

    - name: Install dependencies
      run: |
        pip install sphinx pydata-sphinx-theme myst-parser # Добавь другие зависимости, если нужно

    - name: Build Sphinx documentation
      run: |
        cd docs
        sphinx-build -b html source build/html 

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/html 